
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author aide
 */
public class FrmRegistroMantenimiento extends javax.swing.JDialog {

    /**
     * Creates new form FrmRegistroMantenimiento
     */
    public FrmRegistroMantenimiento(javax.swing.JDialog parent, boolean modal, int ID, float kmr, float kmi) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        txtid.setText(String.valueOf(ID));
        txtKm.setText(String.valueOf(kmr));
        kmini.setText(String.valueOf(kmi));
        txtid.setVisible(false);
        txtKm.setVisible(false);
        kmini.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnAtras = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        RBS = new javax.swing.JRadioButton();
        RBA = new javax.swing.JRadioButton();
        RBN = new javax.swing.JRadioButton();
        RBC = new javax.swing.JRadioButton();
        BtnRealizar = new javax.swing.JButton();
        BtnAtras1 = new javax.swing.JButton();
        txtid = new javax.swing.JTextField();
        kmCarroceria = new javax.swing.JLabel();
        lblkma = new javax.swing.JLabel();
        lblkms = new javax.swing.JLabel();
        lblkmn = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtKm = new javax.swing.JTextField();
        kmini = new javax.swing.JTextField();

        BtnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/regresa_1.png"))); // NOI18N
        BtnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAtrasActionPerformed(evt);
            }
        });
        BtnAtras.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnAtrasKeyPressed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel1.setText("REGISTRO DE MANTENIMIENTO");

        jLabel2.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N
        jLabel2.setText("AFINACIÓN");

        jLabel3.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N
        jLabel3.setText("MEJORA DE CARROCERÍA");

        jLabel4.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N
        jLabel4.setText("SUSPENSIÓN Y FRENOS");

        jLabel5.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N
        jLabel5.setText("NEUMATICOS");

        RBA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBAActionPerformed(evt);
            }
        });

        BtnRealizar.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N
        BtnRealizar.setText("REALIZAR");
        BtnRealizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRealizarActionPerformed(evt);
            }
        });
        BtnRealizar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnRealizarKeyPressed(evt);
            }
        });

        BtnAtras1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/regresa_1.png"))); // NOI18N
        BtnAtras1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAtras1ActionPerformed(evt);
            }
        });
        BtnAtras1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnAtras1KeyPressed(evt);
            }
        });

        kmCarroceria.setText("carroceria");

        lblkma.setText("afinacion");

        lblkms.setText("suspension");

        lblkmn.setText("neumaticos");

        jLabel6.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N
        jLabel6.setText("Km de mantenimiento");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(46, 46, 46)))
                .addGap(18, 18, 18)
                .addComponent(BtnAtras1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(41, 41, 41)
                                    .addComponent(RBA))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(RBC)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(RBS))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(RBN)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblkma, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(kmCarroceria)
                                .addComponent(lblkms))
                            .addComponent(lblkmn)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(BtnRealizar)
                        .addGap(10, 10, 10)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtKm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(82, 82, 82))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(kmini, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 55, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtnAtras1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(RBC)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kmCarroceria, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(RBA, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblkma, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblkms)
                                .addGap(1, 1, 1))
                            .addComponent(RBS)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblkmn)
                                .addComponent(txtKm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(RBN)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kmini, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnRealizar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RBAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RBAActionPerformed

    private void BtnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAtrasActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_BtnAtrasActionPerformed

    private void BtnAtrasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnAtrasKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.setVisible(false);

        }
    }//GEN-LAST:event_BtnAtrasKeyPressed

    private void BtnAtras1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAtras1ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_BtnAtras1ActionPerformed

    private void BtnAtras1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnAtras1KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.setVisible(false);

        }
    }//GEN-LAST:event_BtnAtras1KeyPressed

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained

    }//GEN-LAST:event_formFocusGained
    public void llenarLbls() {
        try {
            BD mBD = new BD();
            mBD.Conectar();
            vehiculo mVehiculo = new vehiculo();
            mVehiculo.setIdentificador(Integer.valueOf(txtid.getText()));
            ResultSet resultado = mBD.ConskmCarroceria(mVehiculo);
            while (resultado.next()) {
                kmCarroceria.setText(resultado.getString(1));
            }
            ResultSet resultado1 = mBD.ConskmNeumaticos(mVehiculo);
            while (resultado1.next()) {
                lblkmn.setText(resultado1.getString(1));
            }
            ResultSet resultado2 = mBD.ConskmFrenos(mVehiculo);
            while (resultado2.next()) {
                lblkms.setText(resultado2.getString(1));
            }
            ResultSet resultado3 = mBD.ConskmAfinacion(mVehiculo);
            while (resultado3.next()) {
                lblkma.setText(resultado3.getString(1));
            }
            float c, a, s, n = 0;
            a = Float.valueOf(lblkma.getText());
            c = Float.valueOf(kmCarroceria.getText());
            s = Float.valueOf(lblkms.getText());
            n = Float.valueOf(lblkmn.getText());
            RBA.setVisible(false);
            RBS.setVisible(false);
            RBC.setVisible(false);
            RBN.setVisible(false);
            if (a >= 5000) {
                RBA.setVisible(true);
            }
            if (s >= 10000) {
                RBS.setVisible(true);
            }
            if (n >= 10000) {
                RBN.setVisible(true);
            }
            if (c >= 50000) {
                RBC.setVisible(true);

            }
        } catch (SQLException ex) {
            Logger.getLogger(FrmConsulta.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(FrmConsulta.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        try {
            llenarLbls();
        } catch (Exception e) {
            System.out.println(e.toString());
        }
    }//GEN-LAST:event_formWindowGainedFocus

    private void BtnRealizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRealizarActionPerformed
        int a = 0;
        int s = 0;
        int c = 0;
        int n = 0;
        float kms = 0;
        float kma = 0;
        float kmn = 0;
        float kmc = 0;
        Mantenimiento mMantenimiento = new Mantenimiento();
        vehiculo mVehiculo = new vehiculo();
        //kmreccorido 
        float KmTotal = Float.valueOf(kmini.getText()) + Float.valueOf(txtKm.getText());
        mMantenimiento.setKm_recorrido(KmTotal);
        mMantenimiento.setId_Vehiculo(Integer.valueOf(txtid.getText()));
        mVehiculo.setIdentificador(Integer.valueOf(txtid.getText()));
        if (RBA.isSelected()) {
            a = 1;
            kma = Float.valueOf(lblkma.getText());
        }
        if (RBS.isSelected()) {
            s = 1;
            kms = Float.valueOf(lblkms.getText());
        }
        if (RBN.isSelected()) {
            n = 1;
            kmn = Float.valueOf(lblkmn.getText());
        }
        if (RBC.isSelected()) {
            c = 1;
            kmc = Float.valueOf(kmCarroceria.getText());
        }
        try {
            BD mBD = new BD();
            if (mBD.Conectar()) {
                mBD.RegisMantenimientos(mMantenimiento, mVehiculo, a, s, n, c, kma, kms, kmc, kmn);
                JOptionPane.showMessageDialog(rootPane, "Mantenimiento realizado");
            }

        } catch (Exception ex) {
            System.out.println(ex.toString());
            JOptionPane.showMessageDialog(rootPane, "Error");
        }

        this.setVisible(false);


    }//GEN-LAST:event_BtnRealizarActionPerformed

    private void BtnRealizarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnRealizarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            int a = 0;
            int s = 0;
            int c = 0;
            int n = 0;
            float kms = 0;
            float kma = 0;
            float kmn = 0;
            float kmc = 0;
            Mantenimiento mMantenimiento = new Mantenimiento();
            vehiculo mVehiculo = new vehiculo();
            //kmreccorido 
            float KmTotal = Float.valueOf(kmini.getText()) + Float.valueOf(txtKm.getText());
            mMantenimiento.setKm_recorrido(KmTotal);
            mMantenimiento.setId_Vehiculo(Integer.valueOf(txtid.getText()));
            mVehiculo.setIdentificador(Integer.valueOf(txtid.getText()));
            if (RBA.isSelected()) {
                a = 1;
                kma = Float.valueOf(lblkma.getText());
            }
            if (RBS.isSelected()) {
                s = 1;
                kms = Float.valueOf(lblkms.getText());
            }
            if (RBN.isSelected()) {
                n = 1;
                kmn = Float.valueOf(lblkmn.getText());
            }
            if (RBC.isSelected()) {
                c = 1;
                kmc = Float.valueOf(kmCarroceria.getText());
            }
            try {
                BD mBD = new BD();
                if (mBD.Conectar()) {
                    mBD.RegisMantenimientos(mMantenimiento, mVehiculo, a, s, n, c, kma, kms, kmc, kmn);
                }

            } catch (Exception ex) {
                System.out.println(ex.toString());
                JOptionPane.showMessageDialog(rootPane, "Error");
            }

            this.setVisible(false);

        }
    }//GEN-LAST:event_BtnRealizarKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmRegistroMantenimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmRegistroMantenimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmRegistroMantenimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmRegistroMantenimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                int id = 0;
                float kmr = 0;
                float kmin = 0;
                FrmRegistroMantenimiento dialog = new FrmRegistroMantenimiento(new javax.swing.JDialog(), true, id, kmr, kmin);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAtras;
    private javax.swing.JButton BtnAtras1;
    private javax.swing.JButton BtnRealizar;
    private javax.swing.JRadioButton RBA;
    private javax.swing.JRadioButton RBC;
    private javax.swing.JRadioButton RBN;
    private javax.swing.JRadioButton RBS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel kmCarroceria;
    private javax.swing.JTextField kmini;
    private javax.swing.JLabel lblkma;
    private javax.swing.JLabel lblkmn;
    private javax.swing.JLabel lblkms;
    private javax.swing.JTextField txtKm;
    private javax.swing.JTextField txtid;
    // End of variables declaration//GEN-END:variables
}
